[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[functions.arb-tick]
  schedule = "* * * * *"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/appspecific/com.tesla.3p.public-key.pem"
  to = "/.netlify/functions/public-key"
  status = 200
  force = true

[[redirects]]
  from = "/callback"
  to = "/callback.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
  force = true

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
