[build]
  functions = "netlify/functions"

[functions.arb-tick]
  schedule = "* * * * *"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/appspecific/com.tesla.3p.public-key.pem"
  to = "/.netlify/functions/public-key"
  status = 200
  force = true

[[redirects]]
  from = "/callback"
  to = "/callback.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
